backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

media_library:
  name: cloudinary
  config:
    cloud_name: da32ufmnf
    api_key: 123757614911618

collections:
  - name: "projects"
    identifier_field: projects
    label: "Projects"
    folder: "content/projects"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "tags"
        label: "Tags"
        widget: "string"
      - name: "hero"
        label: "Hero"
        widget: "image"
        required: true
        choose_url: false
      - name: "img_two"
        label: "Image Two"
        widget: "image"
        required: false
        choose_url: false
      - name: "img_three"
        label: "Image Three"
        widget: "image"
        required: false
        choose_url: false
      - name: "img_four"
        label: "Image Four"
        widget: "image"
        required: false
        choose_url: false
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "timeline"
    identifier_field: timeline
    label: "Timeline"
    folder: "content/timeline"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "img_one"
        label: "Image One"
        widget: "image"
        required: false
        choose_url: false
      - name: "img_two"
        label: "Image Two"
        widget: "image"
        required: false
        choose_url: false
      - name: "img_three"
        label: "Image Three"
        widget: "image"
        required: false
        choose_url: false
      - name: "img_four"
        label: "Image Four"
        widget: "image"
        required: false
        choose_url: false
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
